# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddGrupp(object):
    def setupUi(self, AddGrupp):
        AddGrupp.setObjectName("AddGrupp")
        AddGrupp.resize(300, 300)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        AddGrupp.setFont(font)
        AddGrupp.setTabletTracking(False)
        AddGrupp.setStyleSheet("background-color: rgb(0, 0, 62);")
        self.centralwidget = QtWidgets.QWidget(AddGrupp)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit.setFont(font)
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);\n"
"textr:rgb(255, 255, 255) solid;")
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 200, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(1, 226, 178);\n"
"background-color: rgb(208, 178, 9);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"QPushButton:pressed{\n"
"background-color: rgb(191, 162, 0);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 45, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("Text:rgb(170, 170, 255);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 111, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Text:wihte;\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        AddGrupp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddGrupp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        AddGrupp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddGrupp)
        self.statusbar.setObjectName("statusbar")
        AddGrupp.setStatusBar(self.statusbar)

        self.retranslateUi(AddGrupp)
        QtCore.QMetaObject.connectSlotsByName(AddGrupp)
        self.Ustanovka()

    def retranslateUi(self, AddGrupp):
        _translate = QtCore.QCoreApplication.translate
        AddGrupp.setWindowTitle(_translate("AddUchenik", "Добавление группы"))
        self.pushButton.setText(_translate("AddUchenik", "Добавить группу"))
        self.label.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">Название группы</span></p></body></html>"))
        self.label_2.setText(_translate("AddUchenik", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ffffff;\">Количество</span></p><p align=\"center\"><span style=\" font-size:11pt; color:#ffffff;\">учеников</span></p></body></html>"))


    def Ustanovka(self):
        self.lineEdit.setPlaceholderText("ИКБО-05-21")
        self.lineEdit_2.setPlaceholderText("25")
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit.setFont(font)