# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddGrupp(object):
    def setupUi(self, AddUchenik):
        AddUchenik.setObjectName("AddUchenik")
        AddUchenik.resize(300, 300)
        AddUchenik.setTabletTracking(False)
        AddUchenik.setFocusPolicy(QtCore.Qt.TabFocus)
        AddUchenik.setStyleSheet("background-color: rgb(0, 0, 62);")
        self.centralwidget = QtWidgets.QWidget(AddUchenik)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 10, 151, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lineEdit.setFont(font)
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setToolTip("<html><head/><body><p>апрар</p></body></html>")
        self.lineEdit.setWhatsThis("<html><head/><body><p>цукцук</p></body></html>")
        self.lineEdit.setAccessibleName("")
        self.lineEdit.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"")
        self.lineEdit.setFrame(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 79, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setMouseTracking(False)
        self.lineEdit_2.setAcceptDrops(False)
        self.lineEdit_2.setToolTip("<html><head/><body><p>sdfsfddf </p></body></html>")
        self.lineEdit_2.setWhatsThis("")
        self.lineEdit_2.setAccessibleName("")
        self.lineEdit_2.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"font: 12pt \"Eras Bold ITC\";\n"
"text-color:rgb(255, 255, 255);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 200, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(1, 226, 178);\n"
"background-color: rgb(208, 178, 9);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"QPushButton:pressed{\n"
"background-color: rgb(191, 162, 0);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("Text:rgb(170, 170, 255);\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Text:wihte;\n"
"")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 150, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Eras Medium ITC")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.comboBox.raise_()
        AddUchenik.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddUchenik)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        AddUchenik.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddUchenik)
        self.statusbar.setObjectName("statusbar")
        AddUchenik.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.pu)

        self.retranslateUi(AddUchenik)
        QtCore.QMetaObject.connectSlotsByName(AddUchenik)

    def retranslateUi(self, AddUchenik):
        _translate = QtCore.QCoreApplication.translate
        self.lineEdit.setPlaceholderText("ИКБО-05-21")
        self.lineEdit_2.setPlaceholderText("27")
        self.pushButton.setToolTip(_translate("AddUchenik", "<html><head/><body><p>фыв</p></body></html>"))
        self.pushButton.setText(_translate("AddUchenik", "Добавить ученика"))
        self.label.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">Название группы</span></p></body></html>"))
        self.label_2.setText(_translate("AddUchenik", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; color:#ffffff;\">Количество</span></p><p align=\"center\"><span style=\" font-size:11pt; color:#ffffff;\">учеников</span></p></body></html>"))

    def Ustanovka(self):
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit.setPlaceholderText("ИКБО-05-21")
        self.lineEdit_2.setPlaceholderText("27")
    def pu(self):
        ######
        self.Ustanovka()


