# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adduvg(1).ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bd
from bd import studgroups_add

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 464)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 62);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(150, 220, 501, 41))
        self.comboBox.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color:  rgb(213, 194, 166);")
        self.comboBox.setObjectName("comboBox")



        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 310, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(1, 226, 178);\n"
"background-color: rgb(208, 178, 9);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"QPushButton:pressed{\n"
"background-color: rgb(191, 162, 0);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 130, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("Text:wihte;\n"
"")
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(360, 50, 291, 41))
        self.comboBox_2.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color:  rgb(213, 194, 166);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        #self.comboBox_2.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 60, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("Text:wihte;\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 130, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);\n"
"border: 3px solid;\n"
"border-color:  rgb(213, 194, 166)")
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.Sangu, QtCore.QLocale.Tanzania))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(self.pu)
        self.Ustanovka()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>фыв</p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить ученика"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">Номер зач. книжки</span></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#ffffff;\">ФИО</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))

    def Ustanovka(self):
        mas_name = bd.groups_output()  # Проверяем набор групп
        for i in range(0, len(mas_name)):
            self.comboBox.addItem("")
            self.comboBox.setItemText(i, mas_name[i])

    def pu(self):
        bd.studgroups_add(int(self.lineEdit_4.text()), self.comboBox.currentText())
        self.Ustanovka()
