# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bd

class Ui_AddUchenik(object):
    def setupUi(self, AddUchenik):
        AddUchenik.setObjectName("AddUchenik")
        AddUchenik.resize(347, 312)
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        AddUchenik.setFont(font)
        AddUchenik.setStyleSheet("background-color: rgb(0, 0, 62);")
        self.centralwidget = QtWidgets.QWidget(AddUchenik)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 220, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(1, 226, 178);\n"
"background-color: rgb(208, 178, 9);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"QPushButton:pressed{\n"
"background-color: rgb(191, 162, 0);\n"
"border: 3px solid;\n"
"border-radius: 25 solid ;\n"
"border-color:  rgb(213, 194, 166);}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("Text:wihte;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("Text:wihte;\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 90, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("Text:wihte;\n"
"")
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(170, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);")
        self.dateEdit.setObjectName("dateEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("Text:wihte;\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("Text:wihte;\n"
"")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(208, 178, 9);\n"
"text-color:rgb(255, 255, 255);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        AddUchenik.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddUchenik)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 347, 21))
        self.menubar.setObjectName("menubar")
        AddUchenik.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddUchenik)
        self.statusbar.setObjectName("statusbar")
        AddUchenik.setStatusBar(self.statusbar)

        self.retranslateUi(AddUchenik)
        QtCore.QMetaObject.connectSlotsByName(AddUchenik)
        self.pushButton.clicked.connect(self.pusk)
        self.lineEdit.setPlaceholderText("Иван")
        self.lineEdit_2.setPlaceholderText("Иванов")
        self.lineEdit_3.setPlaceholderText("Иванович")

    def retranslateUi(self, AddUchenik):
        _translate = QtCore.QCoreApplication.translate
        AddUchenik.setWindowTitle(_translate("AddUchenik", "MainWindow"))
        self.lineEdit.setToolTip(_translate("AddUchenik", "<html><head/><body><p>sdfsfddf </p></body></html>"))
        self.lineEdit_2.setToolTip(_translate("AddUchenik", "<html><head/><body><p>sdfsfddf </p></body></html>"))
        self.pushButton.setToolTip(_translate("AddUchenik", "<html><head/><body><p>фыв</p></body></html>"))
        self.pushButton.setText(_translate("AddUchenik", "Добавить ученика"))
        self.label.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" color:#ffffff;\">Имя</span></p></body></html>"))
        self.label_2.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" color:#ffffff;\">Фамилия</span></p></body></html>"))
        self.lineEdit_3.setToolTip(_translate("AddUchenik", "<html><head/><body><p>sdfsfddf </p></body></html>"))
        self.label_3.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" color:#ffffff;\">Отчество</span></p></body></html>"))
        self.label_4.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" color:#ffffff;\">Дата рождения</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("AddUchenik", "<html><head/><body><p><span style=\" color:#ffffff;\">Номер зач. книжки</span></p></body></html>"))
        self.lineEdit_4.setToolTip(_translate("AddUchenik", "<html><head/><body><p>sdfsfddf </p></body></html>"))

    def pusk(self):
        a=self.lineEdit.text()+" "+self.lineEdit_2.text()+" "+self.lineEdit_3.text()
        bd.students_add(a, self.dateEdit.text())
        self.Ustanovka()
    def Ustanovka(self):
        self.lineEdit.setText("")
        self.lineEdit.setPlaceholderText("Иван")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setPlaceholderText("Иванов")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setPlaceholderText("Иванович")
        #self.dateEdit.clear()
        #self.dateEdit.setDate("02.01.2000")

